version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - plex_config:/config
volumes:
  plex_config:
